export const CATEGORIES = [
    { name: 'Edito', value: 6 },
    { name: 'Actu Express', value: 14 },
    { name: '168h au Faso', value: 29 },
    { name: 'Confidentiel', value: 30 },
    { name: 'Politique', value: 15 },
    { name: 'Focale', value: 26 },
    { name: 'Reflex', value: 27 },
    { name: 'Géopolitique', value: 28 },
    { name: 'Société', value: 18 },
    { name: 'Lettre à HS', value: 23 },
    { name: 'Développement', value: 24 },
    { name: 'Coin des femmes', value: 25 },
    { name: 'Point barre', value: 17 },
    { name: 'Profil haut', value: 21 },
    { name: 'Profil bas', value: 22 },
    { name: 'Bendremetrie', value: 16 },
    { name: 'Faits-divers', value: 12 },
    { name: 'Bon à savoir', value: 13 },
    { name: 'Sagesse africaine', value: 20 },
    { name: 'Bendrescopie', value: 7 },
    { name: 'Arrêt sur l’Histoire', value: 8 },
    { name: 'Ils ont dit', value: 9 },
    { name: 'Feu vert', value: 10 },
    { name: 'A bout portant', value: 11 }
];
